"""Response models for the Universal AI Runtime.

Standardizes model outputs for both streaming chunks and non-streaming payloads.
"""



from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class StreamingChunk(BaseModel):

    """Represents an individual chunk of data yielded from a streaming prompt."""



    model_config = ConfigDict(

        extra="allow",

        populate_by_name=True,

    )



    chunk_id: str = Field(

        ...,

        description="A unique tracing identifier for this specific chunk.",

    )

    request_id: str = Field(

        ...,

        description="The matching request ID for context routing.",

    )

    delta_content: str = Field(

        ...,

        description="The incremental text generated in this chunk.",

    )

    finish_reason: str | None = Field(

        default=None,

        description="Reason returned by the provider indicating stream termination.",

    )

    latency_ms: float = Field(

        ...,

        ge=0.0,

        description="Timing measurement from request dispatch to receipt of this chunk.",

    )

    metadata: dict[str, Any] = Field(

        default_factory=dict,

        description="Custom fields for routing middleware or metrics logging.",

    )





class AIResponse(BaseModel):

    """Pydantic model representing a completed response from the Forge runtime."""



    model_config = ConfigDict(

        extra="allow",

        populate_by_name=True,

    )



    response_id: str = Field(

        ...,

        description="A unique tracing identifier for this response.",

    )

    request_id: str = Field(

        ...,

        description="The matching request ID for tracing flow.",

    )

    content: str = Field(

        ...,

        description="The complete output text generated by the provider.",

    )

    token_usage: dict[str, int] = Field(

        default_factory=dict,

        description="Usage statistics (e.g., input_tokens, output_tokens, cached_tokens).",

    )

    finish_reason: str = Field(

        ...,

        description="Reason indicating completion state (e.g. 'stop', 'length').",

    )

    latency_ms: float = Field(

        ...,

        ge=0.0,

        description="Timing measurement representing the total roundtrip latency.",

    )

    metadata: dict[str, Any] = Field(

        default_factory=dict,

        description="Extensible context mapping for telemetry and cache profiles.",

    )

